DOMAINS = [
    ('com.af', 'Afghanistan'),
    ('al', 'Albania'),
    ('dz', 'Algeria'),
    ('as', 'American Samoa'),
    ('ad', 'Andorra'),
    ('co.ao', 'Angola'),
    ('com.ai', 'Anguilla'),
    ('com.ag', 'Antigua and Barbuda'),
    ('com.ar', 'Argentina'),
    ('am', 'Armenia'),
    ('com.au', 'Australia'),
    ('at', 'Austria'),
    ('az', 'Azerbaijan'),
    ('bs', 'Bahamas'),
    ('com.bh', 'Bahrain'),
    ('com.bd', 'Bangladesh'),
    ('by', 'Belarus'),
    ('be', 'Belgium'),
    ('com.bz', 'Belize'),
    ('bj', 'Benin'),
    ('bt', 'Bhutan'),
    ('com.bo', 'Bolivia'),
    ('ba', 'Bosnia and Herzegovina'),
    ('co.bw', 'Botswana'),
    ('com.br', 'Brazil'),
    ('vg', 'British Virgin Islands'),
    ('com.bn', 'Brunei'),
    ('bg', 'Bulgaria'),
    ('bf', 'Burkina Faso'),
    ('bi', 'Burundi'),
    ('com.kh', 'Cambodia'),
    ('cm', 'Cameroon'),
    ('ca', 'Canada'),
    ('cv', 'Cape Verde'),
    ('cat', 'Catalonia'),
    ('cf', 'Central African Republic'),
    ('td', 'Chad'),
    ('cl', 'Chile'),
    ('com.co', 'Colombia'),
    ('co.ck', 'Cook Islands'),
    ('co.cr', 'Costa Rica'),
    ('hr', 'Croatia'),
    ('com.cu', 'Cuba'),
    ('com.cy', 'Cyprus'),
    ('cz', 'Czech Republic'),
    ('cd', 'Democratic Republic of the Congo'),
    ('dk', 'Denmark'),
    ('dj', 'Djibouti'),
    ('dm', 'Dominica'),
    ('com.do', 'Dominican Republic'),
    ('com.ec', 'Ecuador'),
    ('com.eg', 'Egypt'),
    ('com.sv', 'El Salvador'),
    ('ee', 'Estonia'),
    ('com.et', 'Ethiopia'),
    ('com.fj', 'Fiji'),
    ('fi', 'Finland'),
    ('fr', 'France'),
    ('ga', 'Gabon'),
    ('gm', 'Gambia'),
    ('ge', 'Georgia'),
    ('de', 'Germany'),
    ('com.gh', 'Ghana'),
    ('com.gi', 'Gibraltar'),
    ('gr', 'Greece'),
    ('gl', 'Greenland'),
    ('gp', 'Guadeloupe'),
    ('com.gt', 'Guatemala'),
    ('gg', 'Guernsey'),
    ('gy', 'Guyana'),
    ('ht', 'Haiti'),
    ('hn', 'Honduras'),
    ('com.hk', 'Hong Kong'),
    ('hu', 'Hungary'),
    ('is', 'Iceland'),
    ('co.in', 'India'),
    ('co.id', 'Indonesia'),
    ('iq', 'Iraq'),
    ('ie', 'Ireland'),
    ('im', 'Isle of Man'),
    ('co.il', 'Israel'),
    ('it', 'Italy'),
    ('ci', 'Ivory Coast'),
    ('com.jm', 'Jamaica'),
    ('co.jp', 'Japan'),
    ('je', 'Jersey'),
    ('jo', 'Jordan'),
    ('kz', 'Kazakhstan'),
    ('co.ke', 'Kenya'),
    ('ki', 'Kiribati'),
    ('com.kw', 'Kuwait'),
    ('kg', 'Kyrgyzstan'),
    ('la', 'Laos'),
    ('lv', 'Latvia'),
    ('com.lb', 'Lebanon'),
    ('co.ls', 'Lesotho'),
    ('com.ly', 'Libya'),
    ('li', 'Liechtenstein'),
    ('lt', 'Lithuania'),
    ('lu', 'Luxembourg'),
    ('mk', 'Macedonia'),
    ('mg', 'Madagascar'),
    ('mw', 'Malawi'),
    ('com.my', 'Malaysia'),
    ('mv', 'Maldives'),
    ('ml', 'Mali'),
    ('com.mt', 'Malta'),
    ('mu', 'Mauritius'),
    ('com.mx', 'Mexico'),
    ('fm', 'Micronesia, Federated States of'),
    ('md', 'Moldova'),
    ('mn', 'Mongolia'),
    ('me', 'Montenegro'),
    ('ms', 'Montserrat'),
    ('co.ma', 'Morocco'),
    ('co.mz', 'Mozambique'),
    ('com.mm', 'Myanmar'),
    ('com.na', 'Namibia'),
    ('nr', 'Nauru'),
    ('com.np', 'Nepal'),
    ('nl', 'Netherlands'),
    ('co.nz', 'New Zealand'),
    ('com.ni', 'Nicaragua'),
    ('ne', 'Niger'),
    ('com.ng', 'Nigeria'),
    ('nu', 'Niue'),
    ('no', 'Norway'),
    ('com.om', 'Oman'),
    ('com.pk', 'Pakistan'),
    ('ps', 'Palestine'),
    ('com.pa', 'Panama'),
    ('com.pg', 'Papua New Guinea'),
    ('com.py', 'Paraguay'),
    ('com.pe', 'Peru'),
    ('com.ph', 'Philippines'),
    ('pn', 'Pitcairn Islands'),
    ('pl', 'Poland'),
    ('pt', 'Portugal'),
    ('com.pr', 'Puerto Rico'),
    ('com.qa', 'Qatar'),
    ('cg', 'Republic of the Congo'),
    ('ro', 'Romania'),
    ('ru', 'Russia'),
    ('rw', 'Rwanda'),
    ('sh', 'Saint Helena, Ascension and Tristan da Cunha'),
    ('com.vc', 'Saint Vincent and the Grenadines'),
    ('ws', 'Samoa'),
    ('sm', 'San Marino'),
    ('st', 'Sao Tome and Principe'),
    ('com.sa', 'Saudi Arabia'),
    ('sn', 'Senegal'),
    ('rs', 'Serbia'),
    ('sc', 'Seychelles'),
    ('com.sl', 'Sierra Leone'),
    ('com.sg', 'Singapore'),
    ('sk', 'Slovakia'),
    ('si', 'Slovenia'),
    ('com.sb', 'Solomon Islands'),
    ('so', 'Somalia'),
    ('co.za', 'South Africa'),
    ('co.kr', 'South Korea'),
    ('es', 'Spain'),
    ('lk', 'Sri Lanka'),
    ('sr', 'Suriname'),
    ('se', 'Sweden'),
    ('ch', 'Switzerland'),
    ('com.tw', 'Taiwan'),
    ('com.tj', 'Tajikistan'),
    ('co.tz', 'Tanzania'),
    ('co.th', 'Thailand'),
    ('tl', 'Timor-Leste'),
    ('tg', 'Togo'),
    ('tk', 'Tokelau'),
    ('to', 'Tonga'),
    ('tt', 'Trinidad and Tobago'),
    ('tn', 'Tunisia'),
    ('com.tr', 'Turkey'),
    ('tm', 'Turkmenistan'),
    ('co.ug', 'Uganda'),
    ('com.ua', 'Ukraine'),
    ('ae', 'United Arab Emirates'),
    ('co.uk', 'United Kingdom'),
    ('com', 'United States'),
    ('co.vi', 'United States Virgin Islands'),
    ('com.uy', 'Uruguay'),
    ('co.uz', 'Uzbekistan'),
    ('vu', 'Vanuatu'),
    ('co.ve', 'Venezuela'),
    ('com.vn', 'Vietnam'),
    ('co.zm', 'Zambia'),
    ('co.zw', 'Zimbabwe'),
]
