# Generated by Django 5.2.12 on 2026-03-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('search_query', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
