# Generated by Django 5.2.12 on 2026-03-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scrapejob_joblog_businesslisting_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslisting',
            name='maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='collected_listings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='emails_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='processed_listings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='speed',
            field=models.CharField(choices=[('slow', 'Slow'), ('normal', 'Normal'), ('fast', 'Fast')], default='normal', max_length=16),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('completed_with_errors', 'Completed With Errors'), ('failed', 'Failed')], default='queued', max_length=32),
        ),
    ]
