# Generated by Django 6.0.7 on 2026-07-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_scrapejob_source_businesslisting_source_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesslisting',
            options={'ordering': ['-scraped_at']},
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='domain',
            field=models.CharField(default='com', max_length=32),
        ),
    ]
