# Generated by Django 6.0.7 on 2026-07-22 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_businesslisting_options_alter_scrapejob_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name, e.g. Gmail – john@company.com', max_length=255)),
                ('host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=500)),
                ('use_tls', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='If set, campaign will be sent automatically at this time.', null=True),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='auto_campaign_created',
            field=models.BooleanField(default=False, help_text='Whether an email campaign was auto-created for this job'),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Country code e.g. us, uk, in, au (for search engines)', max_length=8),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='search_type',
            field=models.CharField(choices=[('web', 'Web Pages'), ('images', 'Images'), ('videos', 'Videos'), ('news', 'News')], default='web', help_text='Search type for Google (web, images, videos, news)', max_length=16),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='job_filter',
            field=models.ForeignKey(blank=True, help_text='If set, only send to leads from this job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='scraper.scrapejob'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='domain',
            field=models.CharField(blank=True, default='com', max_length=32),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='source',
            field=models.CharField(choices=[('maps', 'Google Maps'), ('google', 'Google Search'), ('bing', 'Bing'), ('yahoo', 'Yahoo'), ('duckduckgo', 'DuckDuckGo'), ('yandex', 'Yandex'), ('ecosia', 'Ecosia'), ('ask', 'Ask.com')], default='maps', max_length=32),
        ),
    ]
