# Generated by Django 6.0.7 on 2026-07-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_smtpprofile_emailcampaign_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='source',
            field=models.CharField(choices=[('maps', 'Google Maps'), ('bing_maps', 'Bing Maps'), ('google', 'Google Search'), ('bing', 'Bing'), ('yahoo', 'Yahoo'), ('duckduckgo', 'DuckDuckGo'), ('yandex', 'Yandex'), ('ecosia', 'Ecosia'), ('ask', 'Ask.com')], default='maps', max_length=32),
        ),
    ]
