# Generated by Django 6.0.7 on 2026-07-22 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_add_bing_maps_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslisting',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this lead'),
        ),
        migrations.CreateModel(
            name='ContactAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('gmail', 'Gmail'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('call', 'Call')], default='email', max_length=20)),
                ('contacted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_attempts', to='scraper.emailcampaign')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_attempts', to='scraper.businesslisting')),
            ],
            options={
                'ordering': ['-contacted_at'],
            },
        ),
    ]
