# Generated by Django 6.0.7 on 2026-07-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_add_contact_attempts_and_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesslisting',
            options={'ordering': ['-is_starred', '-scraped_at']},
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text='Next follow-up date; shown in notifications when due', null=True),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='follow_up_note',
            field=models.TextField(blank=True, help_text="Internal note about this lead's status"),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='is_starred',
            field=models.BooleanField(default=False, help_text='Starred/priority lead — shown above others'),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='lead_status',
            field=models.CharField(choices=[('fresh', 'Fresh'), ('following_up', 'Following Up'), ('converted', 'Converted'), ('stopped', 'Stopped')], default='fresh', help_text='Current pipeline status for this lead', max_length=20),
        ),
    ]
