# Generated by Django 6.0.7 on 2026-07-22 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_alter_businesslisting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_scrape_enabled', models.BooleanField(default=False)),
                ('auto_scrape_phrase', models.CharField(blank=True, default='', max_length=255)),
                ('auto_scrape_locations', models.TextField(blank=True, default='', help_text='Comma-separated locations')),
                ('auto_scrape_max_results', models.PositiveIntegerField(default=200)),
                ('auto_scrape_interval_hours', models.PositiveIntegerField(default=24, help_text='How often to run auto-scrape (hours)')),
                ('auto_scrape_source', models.CharField(default='maps', max_length=20)),
                ('auto_scrape_last_run', models.DateTimeField(blank=True, null=True)),
                ('auto_scrape_next_run', models.DateTimeField(blank=True, null=True)),
                ('auto_campaign_enabled', models.BooleanField(default=False)),
                ('auto_campaign_subject', models.CharField(blank=True, default='Quick question for {name}', max_length=500)),
                ('auto_campaign_body', models.TextField(blank=True, default='Hi {name},\n\nI came across your business and wanted to reach out.\n\nBest,\nYour Name')),
                ('auto_campaign_from_name', models.CharField(blank=True, default='', max_length=255)),
                ('auto_campaign_from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('auto_campaign_delay_minutes', models.PositiveIntegerField(default=30, help_text='Minutes to wait after job completes before sending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_campaign_smtp_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_configs', to='scraper.smtpprofile')),
            ],
            options={
                'verbose_name': 'Auto Config',
            },
        ),
    ]
