# Generated by Django 6.0.7 on 2026-07-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_add_auto_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly label, e.g. 'Dental Outreach – Urgency'", max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='daily_limit',
            field=models.PositiveIntegerField(default=0, help_text='Max emails to send per day. 0 = unlimited. Campaign pauses when this is reached.'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='extra_smtp_profiles',
            field=models.ManyToManyField(blank=True, help_text='Additional SMTP accounts for automatic rotation when one hits its daily limit.', related_name='campaigns', to='scraper.smtpprofile'),
        ),
        migrations.AddField(
            model_name='smtpprofile',
            name='daily_limit',
            field=models.PositiveIntegerField(default=300, help_text='Max emails this profile can send per day (e.g. 300 for Gmail free, 0 = unlimited).'),
        ),
    ]
