# Generated by Django 6.0.7 on 2026-07-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_add_daily_limit_email_templates_smtp_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoconfig',
            name='global_daily_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum emails sent per day across ALL campaigns combined. 0 = no global cap.'),
        ),
        migrations.AddField(
            model_name='autoconfig',
            name='global_smtp_profiles',
            field=models.ManyToManyField(blank=True, help_text='Global SMTP rotation pool — any campaign without its own extra profiles will use these.', related_name='global_auto_configs', to='scraper.smtpprofile'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='ai_variation',
            field=models.BooleanField(default=False, help_text='When enabled, subtly varies the subject line and opening line of each email to avoid spam detection.'),
        ),
    ]
