# Generated by Django 6.0.7 on 2026-07-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_remove_pre_send_contact_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='send_mode',
            field=models.CharField(choices=[('burst', 'Burst — send all at once'), ('fast', 'Fast — 3 s between emails'), ('slow', 'Slow — 7–15 s between emails')], default='fast', help_text='Controls sending speed to protect your SMTP from bans.', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='ai_variation',
            field=models.BooleanField(default=True, help_text='When enabled, subtly varies the subject line and opening line of each email to avoid spam detection.'),
        ),
    ]
