# Generated by Django 6.0.7 on 2026-07-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_add_send_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpprofile',
            name='password',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
