# Generated by Django 6.0.7 on 2026-07-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_smtp_password_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpprofile',
            name='from_email',
            field=models.EmailField(blank=True, default='', help_text='From address shown to recipients. Leave blank to use Username/Email.', max_length=254),
        ),
        migrations.AddField(
            model_name='smtpprofile',
            name='from_name',
            field=models.CharField(blank=True, default='', help_text='Display name shown to recipients, e.g. John Smith', max_length=255),
        ),
        migrations.AddField(
            model_name='smtpprofile',
            name='reply_to',
            field=models.EmailField(blank=True, default='', help_text='Reply-To address (optional). Leave blank to use From email.', max_length=254),
        ),
    ]
